[tool.poetry]
name = "ALEX-classify"
version = "0.0.0"
description = "ALEX classify is a python library that provides tools to classify SMEs."
authors = ["Yassin Kortam"]
license = "MIT"
readme = "README.md"