[tool.poetry]
name = "classify_entity"
version = "0.0.0"
description = "Classify entity is a python library that provides tools to classify SMEs."
authors = ["Yassin Kortam <yassinkortam@g.ucla.edu>"]
license = "MIT"
readme = "README.md"